// flow-typed signature: add54c5ff35a3f556f198de19b8cf6c7
// flow-typed version: <<STUB>>/eslint-import-resolver-alias_v^1.0.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-import-resolver-alias/index' {
  declare module.exports: $Exports<'eslint-import-resolver-alias'>;
}
declare module 'eslint-import-resolver-alias/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-alias'>;
}
